repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args: [--args=--escape=false]
      - id: terraform_tflint
        args: [--args=--config=../../.tflint.hcl]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
